### ISSUE TITLE
Warning about unverified HTTPS request

### ISSUE THREAD

**Issue by ktuulos** [appzer/zabbix-pushsafer#1]
When executing the script (2017-09-15 14:10:54 version), it gives following warning:

/usr/local/lib/python2.7/dist-packages/urllib3-1.22-py2.7.egg/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

This does not prohibit using the script - messages are delivered successfully.

**Comment by appzer** [comment]
thats correct! 
zabbix (not secured) sends the payload (title,message) to our SSL secured server > https://www.pushsafer.com/api

To solve the issue you can create a certificate,like here: [https://stackoverflow.com/questions/30405867/how-to-get-python-requests-to-trust-a-self-signed-ssl-certificate](https://stackoverflow.com/questions/30405867/how-to-get-python-requests-to-trust-a-self-signed-ssl-certificate)

Kevin

**Comment by piotrgawor** [comment]
You can also add:
```
import urllib3
urllib3.disable_warnings()
```
at the top of script.
