### ISSUE TITLE
Other parameter in Client("").send_message

### ISSUE THREAD

**Issue by piotrgawor** [appzer/zabbix-pushsafer#2]
Are the other parameters described somewhere?
Client("").send_message(message, subject, "", ....
I want to send different icon and sound in notification.

**Comment by appzer** [comment]
Hi you can take a look at the phyton package which is used by the zabbix plugin
[https://github.com/appzer/python-pushsafer](https://github.com/appzer/python-pushsafer)

Or you can create diffrent **ALIASES** with diffrent icons or sounds in the pushsafer dashboard.
This new alias key you have to use as private key.

Kevin

**Comment by appzer** [comment]
yes, you can do like this:
`Client("").send_message(message, title, device, icon, sound, vibration, url, urltitle, time2live, priority, retry, expire, answer, picture1, picture2, picture3)`
