### ISSUE TITLE
ImportError: No module named pushsafer

### ISSUE THREAD

**Issue by khoavan001** [appzer/zabbix-pushsafer#5]
hi,
i am using CentOS 7.
i have already install : pip install python-pushsafer . when run script ./zabbix-pushsafer-centOS.sh , it showing me error: ImportError: No module named pushsafer

[root@localhost alertscripts]# ./zabbix-pushsafer-centOS.sh
Traceback (most recent call last):
  File "./zabbix-pushsafer-centOS.sh", line 20, in <module>
    import pushsafer
ImportError: No module named pushsafer

Can you help me? any packages is needed?

**Comment by appzer** [comment]
please check if the python pushsafer package installed correctly.
You can test it like described here:
[https://github.com/appzer/python-pushsafer](https://github.com/appzer/python-pushsafer)

**Comment by khoavan001** [comment]
hi,
successful install package.
try to test script with the parameters as below:
sendto <pushsafer privatekey>
but i got this message from zabbix server:
:Connection timeout of 3 seconds exceeded when connecting to Zabbix server "10.239.72.229".
72.229 is my zabbix web server
is there any needed SMTP configure?

**Comment by appzer** [comment]
no, please try this one also: [https://github.com/appzer/zabbix-pushsafer/blob/master/zabbix-pushsafer.py](https://github.com/appzer/zabbix-pushsafer/blob/master/zabbix-pushsafer.py)

**Comment by jimmys01** [comment]
I also get the same error. When i run it through the command line everything is OK thought

**Comment by appzer** [comment]
did you try all steps above?

**Comment by jimmys01** [comment]
Yes I have.

**Comment by appzer** [comment]
what script you tried? zabbix-pushsafer.py or zabbix-pushsafer-centOS.sh!
What operating system you use?

**Comment by jimmys01** [comment]
I have used both zabbix-pushsafer.py and zabbix-pushsafer-centOS.sh with the same result

```
 File "/usr/lib/zabbix/alertscripts/zabbix-pushsafer-centOS.sh", line 20, in <module>
import pushsafer
ImportError: No module named pushsafe
```

 Ubuntu 18.04.5 LTS

As i said, running it from the cmd the script works fine.

THanks for your time!!

**Comment by appzer** [comment]
please try to run the pushsafer.py script on the CLI to test if script work and/or plugin works!
For it works fine!

`python zabbix-pushsafer.py PRIVATEKEY MESSAGE TITLE`

**Comment by jimmys01** [comment]
In the cli it works fine
in the zabbix it is not. Your library works fine. in conjuction with the zabbix server it is not.
![εικόνα](https://user-images.githubusercontent.com/17748323/91037681-1b4c3380-e612-11ea-85ca-a0c2b20a46e4.png)

**Comment by appzer** [comment]
please try to get help in the zabbix forum, i do not have an anwser for that issue!

Kevin
